repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: [--config=ruff.toml]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: [--config-file, mypy.ini, --install-types, --non-interactive]
        additional_dependencies:
          - types-PyYAML

default_language_version:
  python: python3.11
