[tool.ruff]
line-length = 100
target-version = "py311"
extend-exclude = ["state", "backup", "memoria/db", "artifacts"]

[tool.ruff.lint]
select = ["E", "F", "I"]  # pycodestyle, pyflakes, isort
fixable = ["I"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
strict = false
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
