line-length = 130
target-version = "py311"

[lint]
select = ["E", "F", "I", "B", "UP", "W"]
# Ignoramos temporalmente las advertencias que te frenaban:
ignore = ["E501", "F401", "F841", "UP035", "UP038", "B904", "B007"]
