name: Lint & Typecheck
on:
  push:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps (if requirements.txt exists)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
