name: Lint & Typecheck
on:
  push:
  pull_request:

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install project deps (if requirements.txt exists)
        if: hashFiles('requirements.txt') != ''
        run: pip install -r requirements.txt

      - name: Install linters
        run: pip install ruff mypy pre-commit

      - name: Ruff (lint)
        run: ruff check .

      - name: Ruff (format check)
        run: ruff format --check .

      - name: Mypy (type check)
        run: mypy .

      # Paridad con local: corre exactamente lo de .pre-commit-config.yaml
      - name: pre-commit (parity with local)
        run: pre-commit run --all-files --show-diff-on-failure
