name: Lint & Typecheck
on:
  push:
  pull_request:

jobs:
  lint-type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -U pip
      - name: Install deps (if requirements.txt exists)
        if: ${{ hashFiles('requirements.txt') != '' }}
        run: pip install -r requirements.txt
      - run: pip install ruff mypy
      - run: ruff check .
      - run: ruff format --check .
      - run: mypy .
